apiVersion: monitoring.coreos.com/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: monitoring
spec:
  resources:
    limits:
      cpu: 20m
      memory: 40Mi
    requests:
      cpu: 10m
      memory: 20Mi
  # nodeSelector:
  #   node.kubernetes.io/role: "infra"
  # tolerations:
  #   - key: node.kubernetes.io/role
  #     value: infra
  #     operator: Equal
  #     effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi