bootstrap-init:
	furyctl bootstrap init 

bootstrap-plan:
	furyctl bootstrap apply --dry-run

bootstrap-apply:
	furyctl bootstrap apply

cluster-init:
	furyctl cluster init 

cluster-plan:
	furyctl cluster apply --dry-run

cluster-apply:
	furyctl cluster apply

