# simple nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-complains
  labels:
    app: complains-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complains-app
  template:
    metadata:
      labels:
        app: complains-app
    spec:
      containers:
      - name: complains-web
        image: nginxinc/nginx-unprivileged:1.25
        securityContext:
          runAsUser: 101
          runAsNonRoot: true
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: complains-app-service
  labels:
    app: complains-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: complains-app